//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Business_Online_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Address()
        {
            this.Customers = new HashSet<Customer>();
            this.Customers1 = new HashSet<Customer>();
        }
    
        public long Add_ID { get; set; }
        public string Add_Street_Number { get; set; }
        public string Add_Street_Name { get; set; }
        public string Add_Apartment_Number { get; set; }
        public Nullable<int> Add_City { get; set; }
        public Nullable<int> Add_State_or_Province { get; set; }
        public Nullable<int> Add_Country { get; set; }
        public string Add_Postal_Code { get; set; }
    
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        public virtual State_Or_Provence State_Or_Provence { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<Customer> Customers1 { get; set; }
    }
}
