//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Business_Online_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.Addresses = new HashSet<Address>();
            this.Cities = new HashSet<City>();
            this.State_Or_Provence = new HashSet<State_Or_Provence>();
        }
    
        public int Cont_ID { get; set; }
        public string Cont_Name { get; set; }
        public string Cont_Code { get; set; }
    
        public virtual ICollection<Address> Addresses { get; set; }
        public virtual ICollection<City> Cities { get; set; }
        public virtual ICollection<State_Or_Provence> State_Or_Provence { get; set; }
    }
}
