//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Business_Online_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Claim
    {
        public long Claim_ID { get; set; }
        public string Clain_Subject { get; set; }
        public string Claim_Description { get; set; }
        public Nullable<long> Payment_ID { get; set; }
        public Nullable<long> Shipment_ID { get; set; }
        public long Customer_ID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Payment Payment { get; set; }
    }
}
