//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Business_Online_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Line_Item
    {
        public Order_Line_Item()
        {
            this.Shipments = new HashSet<Shipment>();
        }
    
        public long Ord_Line_ID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Unit_Price { get; set; }
        public Nullable<decimal> Sub_Total { get; set; }
        public Nullable<long> Product_Item_ID { get; set; }
        public long Order_Number { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual ICollection<Shipment> Shipments { get; set; }
    }
}
