//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Business_Online_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.Order_Line_Item = new HashSet<Order_Line_Item>();
            this.Payments = new HashSet<Payment>();
        }
    
        public long Ord_Number { get; set; }
        public Nullable<System.DateTime> Ord_Date { get; set; }
        public Nullable<int> Ord_Status { get; set; }
        public Nullable<long> Cust_ID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<Order_Line_Item> Order_Line_Item { get; set; }
        public virtual Order_State Order_State { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
