//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Business_Online_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Item_State
    {
        public Product_Item_State()
        {
            this.Product_Item = new HashSet<Product_Item>();
        }
    
        public int Pro_Item_State_ID { get; set; }
        public string Pro_Item_State_Description { get; set; }
    
        public virtual ICollection<Product_Item> Product_Item { get; set; }
    }
}
