//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Business_Online_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Item
    {
        public long Pro_Item_ID { get; set; }
        public string Pro_Item_Serial_Number { get; set; }
        public long Product_Number { get; set; }
        public int Pro_Item__State { get; set; }
        public int Supplier_ID { get; set; }
    
        public virtual Product_Item_State Product_Item_State { get; set; }
        public virtual Product_Specification Product_Specification { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
