//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Business_Online_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Specification
    {
        public Product_Specification()
        {
            this.Customer_Review = new HashSet<Customer_Review>();
            this.Product_By_Supplier = new HashSet<Product_By_Supplier>();
            this.Product_Item = new HashSet<Product_Item>();
            this.Shopping_Cart_Items = new HashSet<Shopping_Cart_Items>();
        }
    
        public long Pro_Number { get; set; }
        public string Pro_Name { get; set; }
        public Nullable<decimal> Pro_Price { get; set; }
        public Nullable<int> Pro_Available_Balance { get; set; }
        public string Pro_OnOrder_Quantity { get; set; }
        public Nullable<int> Pro_Return_Balance { get; set; }
        public Nullable<int> Por_OnExchange_Balance { get; set; }
        public Nullable<decimal> Pro_Weight { get; set; }
        public Nullable<long> Dimension_ID { get; set; }
        public Nullable<int> Pro_Category_ID { get; set; }
        public string Pro_Image_File_Name { get; set; }
        public string Pro_Brand { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Customer_Review> Customer_Review { get; set; }
        public virtual ICollection<Product_By_Supplier> Product_By_Supplier { get; set; }
        public virtual Product_Dimension Product_Dimension { get; set; }
        public virtual ICollection<Product_Item> Product_Item { get; set; }
        public virtual ICollection<Shopping_Cart_Items> Shopping_Cart_Items { get; set; }
    }
}
