//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Business_Online_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Dimension
    {
        public Product_Dimension()
        {
            this.Product_Specification = new HashSet<Product_Specification>();
        }
    
        public long Dim_ID { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Height { get; set; }
        public int Unit_ID { get; set; }
    
        public virtual Dimension_Unit Dimension_Unit { get; set; }
        public virtual ICollection<Product_Specification> Product_Specification { get; set; }
    }
}
