//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Business_Online_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipment
    {
        public long Ship_ID { get; set; }
        public Nullable<System.DateTime> Ship_DateTime { get; set; }
        public Nullable<decimal> Ship_Cost { get; set; }
        public long Ship_Origin { get; set; }
        public long Ship_Destination { get; set; }
        public int Ship_Service_Type { get; set; }
        public long Customer_ID { get; set; }
        public long Product_Item_ID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Order_Line_Item Order_Line_Item { get; set; }
        public virtual Shipment_Service_Type Shipment_Service_Type { get; set; }
    }
}
