//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Business_Online_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shopping_Cart_Items
    {
        public long CItem_ID { get; set; }
        public long CItem_Shopping_Cart_ID { get; set; }
        public long CItem_Product_Number { get; set; }
        public Nullable<int> CItem_Quantity { get; set; }
        public Nullable<decimal> CItem_Sub_Total { get; set; }
    
        public virtual Product_Specification Product_Specification { get; set; }
        public virtual Shopping_Cart Shopping_Cart { get; set; }
    }
}
