//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Business_Online_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shopping_Cart
    {
        public Shopping_Cart()
        {
            this.Shopping_Cart_Items = new HashSet<Shopping_Cart_Items>();
        }
    
        public long Cart_ID { get; set; }
        public Nullable<System.DateTime> Cart_Date_And_Time { get; set; }
        public Nullable<int> Cart_Number_of_Products { get; set; }
        public Nullable<decimal> Cart_Total_Price { get; set; }
        public Nullable<int> Cart_State { get; set; }
        public Nullable<long> Cart_Customer_ID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<Shopping_Cart_Items> Shopping_Cart_Items { get; set; }
        public virtual Shopping_Cart_State Shopping_Cart_State { get; set; }
    }
}
