//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Business_Online_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public Supplier()
        {
            this.Product_By_Supplier = new HashSet<Product_By_Supplier>();
            this.Product_Item = new HashSet<Product_Item>();
            this.Supplier_Contact_Preson = new HashSet<Supplier_Contact_Preson>();
        }
    
        public int Sup_ID { get; set; }
        public string Sup_Name { get; set; }
        public string Sup_URL { get; set; }
    
        public virtual ICollection<Product_By_Supplier> Product_By_Supplier { get; set; }
        public virtual ICollection<Product_Item> Product_Item { get; set; }
        public virtual ICollection<Supplier_Contact_Preson> Supplier_Contact_Preson { get; set; }
    }
}
