//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Business_Online_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier_Contact_Preson
    {
        public int Sup_Contact_Preson_ID { get; set; }
        public string Sup_Contact_Preson_Name { get; set; }
        public string Sup_Contact_Preson_Email { get; set; }
        public string Sup_Contact_Preson_Cellpone { get; set; }
        public string Sup_Contact_Preson_Phone_Extension { get; set; }
        public int Supplier_ID { get; set; }
    
        public virtual Supplier Supplier { get; set; }
    }
}
